name: youtube
description: A package to get youtube video information and thumbnail in multiple quality.
version: 2.0.0
homepage: https://rohitchouhan.com
repository: https://github.com/rohit-chouhan/youtube-flutter

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

screenshots:
  - description: "Youtube Logo, Copyright by youtube.com"
    path: logo.png

topics:
  - youtube
  - yt
  - thumbnail
  - googleapis
  - google
